Added Docker configuration
wolox-training/tag-rails pull request #25
Opened 2019-08-16 20:33 UTC by tagonzalez

## Summary

Added Docker configuration for Rails app.
The following commands need to be executed for the app to work properly.
```bash
# Build the docker image
docker-compose build

# Start the app, will display a warning about the lack of dbs
docker-compose up

# Create and migrate db
docker-compose run web db:create db:migrate
```

Now the app can be started with 
```docker-compose up```
And stopped with
```docker-compose down```

To use the rails console
```docker-compose run web rails c```
## Notes
- `docker-compose.yml` file added to coordinate all services: the web server, `sidekiq`, `redis` (needed for sidekiq), and `postgres`
- `Dockerfile` specifies the steps to take to prepare the environment and build the image
- `entrypoint.sh` is necessary to avoid a [common Rails problem](https://docs.docker.com/compose/rails/) in Docker that can't start a server because there is a remaining `.pid` file in the `tmp` directory
- `.dockerignore` to specify the files that must not be copied from the repository to the working directory in the Docker environment

## Screenshots

### Startup of web server, sidekiq, postgres and redis using `docker-compose`
![docker-compose up](https://user-images.githubusercontent.com/14864633/63196493-cadbe680-c04b-11e9-925d-354d4f4f56ba.png)

### Welcome screen in localhost:3000
![docker-welcom](https://user-images.githubusercontent.com/14864633/63196495-cd3e4080-c04b-11e9-8453-825889bcb293.png)

### Creating a User and a Book from rails console in docker environment
![creates-docker-rails-c](https://user-images.githubusercontent.com/14864633/63196502-d0393100-c04b-11e9-8ed3-74f41d9efcbd.png)
### User sign in via Postman
![docker-sign-in](https://user-images.githubusercontent.com/14864633/63196509-d5967b80-c04b-11e9-86f0-117e928e6eba.png)

### Creating a Rent via Postman and mail received in Mailtrap
![create-rent](https://user-images.githubusercontent.com/14864633/63196519-d9c29900-c04b-11e9-877b-541b3f1b5a3e.png)

![mailtrap](https://user-images.githubusercontent.com/14864633/63196561-eb0ba580-c04b-11e9-96d2-092f45362aa7.png)

### Admin panel
![admin](https://user-images.githubusercontent.com/14864633/63196567-ef37c300-c04b-11e9-9785-241bc2f59ddb.png)

2019-08-20 15:44 UTC, marcegl91 requested changes

2019-08-20 15:44 UTC, marcegl91 commented on Dockerfile
> +COPY Gemfile /myapp/Gemfile
Why do you copy the Gemfile, install and run bundle and then copy the rest of the project. Wouldn't be easier just to copy everything and then install and run bundle?

2019-08-20 15:44 UTC, marcegl91 commented on docker-compose.yml
> +      - 'postgres'
Why this is quoted but in the web services is not quoted?

2019-08-20 15:44 UTC, marcegl91 commented on entrypoint.sh
> +rm -f /app/tmp/pids/server.pid
This absolute path is consistent with the container in Docker?

2019-08-20 15:49 UTC, marcegl91 commented on Dockerfile
> +ENTRYPOINT ["entrypoint.sh"]
Do you need to set an entrypoint? The "entrypoint.sh" script will run everytime you do docker run, ie when you start a web server and also when you start a rails console. Also, this is repeated with what is defined in the web/command line.

2019-08-20 16:51 UTC, tagonzalez commented on Dockerfile
> +COPY Gemfile /myapp/Gemfile
I thought the same thing, it would be easier to script. 

I'm trying to find out why every article/doc that I find has this convention. My guess is that it's a _fail fast_ practice, where you first check if every dependency can be installed and, if everything gets to install correctly, then you copy the entire directory (which may take a considerable amount of time if the project is big enough).

[Here's another guess that I found on StackOverflow.](https://stackoverflow.com/questions/50083406/why-would-you-copy-your-gemfile-lock-into-docker-then-immediately-overwrite-it)

2019-08-20 17:14 UTC, tagonzalez commented on Dockerfile
> +ENTRYPOINT ["entrypoint.sh"]
I understand, changes made in latest commit!

2019-08-20 17:14 UTC, tagonzalez commented on entrypoint.sh
> +rm -f /app/tmp/pids/server.pid
It isn't, another typo.

Modified in latest commits!

2019-08-20 17:14 UTC, tagonzalez commented on docker-compose.yml
> +      - 'postgres'
This is a typo. Good eye! I'm pretty sure that it doesn't change functionality but it'll be better for code consistency to clean it up.

Quotes removed in latest commits.

2019-08-20 18:54 UTC, marcegl91 requested changes

2019-08-20 18:54 UTC, marcegl91 commented on entrypoint.sh
> +
After your last commit, this file is unused (the only place where this file is used is at setting the entrypoint) and because you deleted the rm -f in the docker-compose.yml, the server.pid file is not deleted anywhere. But I'm not so sure if you need to delete it or not, so be aware that this script is not running at all. Also, please read this to understand differences between CMD and ENTRYPOINT on Docker:

https://stackoverflow.com/questions/21553353/what-is-the-difference-between-cmd-and-entrypoint-in-a-dockerfile

I'd try to build everything from scratch again in Docker, removing the containers that were already generated (`docker ps -a`, `docker container ls -a`, `docker image ls -a`), and checking if everything works out of the box without this file.

2019-08-20 18:54 UTC, marcegl91 commented on Dockerfile
> +COPY Gemfile /myapp/Gemfile
It doesn't make a lot of sense to me but if it's in the official documentation... Just be aware that each RUN, COPY and ADD command creates a new layer:

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

2019-08-20 21:16 UTC, tagonzalez commented on entrypoint.sh
> +
It's true that this file isn't running and everything works correctly.
The file will be removed in the latest commit.

2019-08-21 14:26 UTC, marcegl91 approved these changes

2019-08-21 17:03 UTC, merged